---

- name: Simple playbook to install httpd package
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: Install httpd package
    yum: name=httpd state=latest

  - name: Copy index.html file
    copy: src=/tmp/index.html dest=/var/www/html mode=644 backup=yes

  - name: Start httpd service
    service: name=httpd state=started
